name = "QuantumRealm"
uuid = "25edebd6-6144-4a5c-9bf3-ce9592f90e67"
authors = ["Yi-Te Huang"]
version = "0.1.0"

[deps]
BaryRational = "91aaffc3-5777-4842-85b7-5d3d5d6a3494"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
HierarchicalEOM = "a62dbcb7-80f5-4d31-9a88-8b19fd92b128"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.10"
